---

## Init

- name: Ensure project directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_project_path }}"
    - "{{ docker_project_path }}/conf"
    - "{{ docker_project_path }}/data"
  tags: ["init"]

## Configure

- name: Copy configuration files
  ansible.builtin.copy:
    src: "./"
    dest: "{{ docker_project_path }}/"
    directory_mode : '0755'
    mode:            '0644'

- name: Template conf/app.ini
  ansible.builtin.template:
    src: ./conf/app.ini.j2
    dest: "{{ docker_project_path }}/conf/app.ini"
    mode: '0664'
    backup: true
  notify: Restart gogs

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_project_path }}/docker-compose.yml"
    mode: '0644'
    validate: "{{ docker_cli }} compose -f %s config"
    backup: true

## Run

- name: Start app
  ansible.builtin.include_role: { name: djuuu.docker_project, tasks_from: compose-up }
